### ISSUE TITLE
[Sugerencia] Interruptores y bombillas inteligentes

### ISSUE THREAD

**Issue by AP-80** [domoticafacilconjota/capitulos#12]
**Me gustaría sugerir que hagas un vídeo con el siguiente contenido:**

Buenas noches Jota, como te comenté me gustaría saber que opciones existen para hacer que las lamparas de pie y mesita de noche con interruptor en el cableado funcionen y se integren correctamente, sin estar pendiente de si la llave está cerrada o abierta. La solución de los Shelly para interruptores conmutados está muy bien, pero en los casos de un único interruptor si lo abre la aplicación para apagarlo desde el interruptor se tiene que pulsar dos veces, además en los casos de lamparas sería difícil hacer una instalación que quedara limpia. La verdad es que está parte de la domotización es muy interesante también, porque al ir instalado dispositivos vas descubriendo cosas que no funcionan exactamente como uno quisiera.

Muchas gracias por el gran trabajo que estas haciendo.

Saludos.

Antonio

**Comment by domoticafacilconjota** [comment]
Con los Shelly sí que lo puedes hacer aunque no sea una conmutada. Me parece buen vídeo. A ver qué opina la gente.

**Comment by domoticafacilconjota** [comment]
Lo acabo de grabar.

**Comment by AP-80** [comment]
Eres un máquina, muchas gracias.

Antonio

Enviado desde mi iPhone
