### ISSUE TITLE
[NuevoFlow] Apagar bombillas Wifi tras reinicio por corte de luz 

### ISSUE THREAD

**Issue by benjaminmupe** [domoticafacilconjota/capitulos#19]
tras un corte de luz y después de reestablecerse el servicio y reiniciar home assistant, hacer que se apaguen todas las bombillas wifi que no se pueden configurar con el status de off y que no se queden encendidas
**Notas del autor**
Gracias

**Comment by domoticafacilconjota** [comment]
Acabo de grabar un vídeo sobre el tema. No es exactamente lo mismo, pero quizás te pueda valer. Cierro el issue, si cuando salga el vídeo no es lo que querías, haz un comentario y lo miramos.
