### ISSUE TITLE
[NuevoFlow] Cómo crear y usar un temporizador variable configurable mediante una slide bar

### ISSUE THREAD

**Issue by benjaminmupe** [domoticafacilconjota/capitulos#23]
Se trata de un temporizador que valga para activar un switch o light seleccionando el tiempo que lo queremos dejar activo mediante un control deslizante. Por ejemplo ,1 hora máximo configurable en pasos de 1 minuto.
No sé si se podrá hacer un timer que empieze a contar el tiempo que lleva activo un switch, ascendiente, que diga los minutos que lleva activo un relé...
**Notas del autor**
Con tiempo ascendiente o descendiente si es posible.

**Comment by Piton6** [comment]
+1

**Comment by domoticafacilconjota** [comment]
¡Hecho! Aunque la verdad es que no entendí esta parte: "No sé si se podrá hacer un timer que empieze a contar el tiempo que lleva activo un switch, ascendiente, que diga los minutos que lleva activo un relé..."
