### ISSUE TITLE
[NuevoFlow] Encender bombilla al detectar movimiento

### ISSUE THREAD

**Issue by IsilionKodi** [domoticafacilconjota/capitulos#43]
**Encender bombilla al detectar movimiento**
#La idea es sencilla, hacer que una o varias bombillas se enciendan al pasar por delante de un detector de movimiento, y se apaguen al cabo de X segundos.
Como alternativa, también valdría con un detector de apertura de una puerta/ventana.

**Notas del autor**
Sería interesante añadirle la opción de que solo se ejecute en un intervalo de tiempo, por ejemplo, del anocheder al amanecer del día siguiente.

**Comment by IsilionKodi** [comment]
![image](https://user-images.githubusercontent.com/39967967/101534651-be457500-3997-11eb-983e-fc4c187e32cc.png)
Lo tengo así definido, aunque seguro que hay alguna forma mejor para que quede más depurado y demás...

`[{"id":"6e5a8a30.0c25d4","type":"comment","z":"fa925e46.718e9","name":"Sensor de Presencia Entrada","info":"","x":160,"y":240,"wires":[]},{"id":"a01a594c.311b48","type":"api-call-service","z":"fa925e46.718e9","name":"Encender Bombilla","server":"e97fecdf.962f6","version":1,"debugenabled":true,"service_domain":"light","service":"turn_on","entityId":"light.bombilla_entrada_1_light","data":"{\"entity_id\":\"light.bombilla_entrada_1_light\",\"brightness_pct\":10}","dataType":"json","mergecontext":"","output_location":"","output_location_type":"none","mustacheAltTags":false,"x":610,"y":320,"wires":[[]]},{"id":"257690b8.04e1d","type":"api-call-service","z":"fa925e46.718e9","name":"Apagar Bombilla","server":"e97fecdf.962f6","version":1,"debugenabled":false,"service_domain":"light","service":"turn_off","entityId":"light.bombilla_entrada_1_light","data":"","dataType":"json","mergecontext":"","output_location":"","output_location_type":"none","mustacheAltTags":false,"x":780,"y":360,"wires":[[]]},{"id":"7d7296b9.25fc28","type":"delay","z":"fa925e46.718e9","name":"Espera 75 seg.","pauseType":"delay","timeout":"75","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":600,"y":360,"wires":[["257690b8.04e1d"]]},{"id":"54bf831c.5a352c","type":"bigtimer","z":"fa925e46.718e9","outtopic":"","outpayload1":"","outpayload2":"","name":"Horario Programado","comment":"","lat":"40.477967","lon":"-3.659325","starttime":"5004","endtime":"5003","starttime2":0,"endtime2":0,"startoff":"-5","endoff":"-2","startoff2":0,"endoff2":0,"offs":0,"outtext1":"","outtext2":"","timeout":1440,"sun":true,"mon":true,"tue":true,"wed":true,"thu":true,"fri":true,"sat":true,"jan":true,"feb":true,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":true,"dec":true,"day1":0,"month1":0,"day2":0,"month2":0,"day3":0,"month3":0,"day4":0,"month4":0,"day5":0,"month5":0,"day6":0,"month6":0,"day7":0,"month7":0,"day8":0,"month8":0,"day9":0,"month9":0,"day10":0,"month10":0,"day11":0,"month11":0,"day12":0,"month12":0,"d1":0,"w1":0,"d2":0,"w2":0,"d3":0,"w3":0,"d4":0,"w4":0,"d5":0,"w5":0,"d6":0,"w6":0,"xday1":0,"xmonth1":0,"xday2":0,"xmonth2":0,"xday3":0,"xmonth3":0,"xday4":0,"xmonth4":0,"xday5":0,"xmonth5":0,"xday6":0,"xmonth6":0,"xd1":0,"xw1":0,"xd2":0,"xw2":0,"xd3":0,"xw3":0,"xd4":0,"xw4":0,"xd5":0,"xw5":0,"xd6":0,"xw6":0,"suspend":false,"random":false,"randon1":false,"randoff1":false,"randon2":false,"randoff2":false,"repeat":false,"atstart":true,"odd":false,"even":false,"x":380,"y":340,"wires":[[],["a01a594c.311b48","7d7296b9.25fc28"],[]]},{"id":"b8592015.9fd5f","type":"inject","z":"fa925e46.718e9","name":"Automático","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"auto","payloadType":"str","x":160,"y":300,"wires":[["54bf831c.5a352c"]]},{"id":"a7b7e2ce.2729e","type":"inject","z":"fa925e46.718e9","name":"Desactivar","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"stop","payloadType":"str","x":160,"y":340,"wires":[["54bf831c.5a352c"]]},{"id":"def9da8e.4be0c8","type":"server-state-changed","z":"fa925e46.718e9","name":"Movimiento Entrada","server":"e97fecdf.962f6","version":1,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"binary_sensor.sensor_presencia_entrada_occupancy","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"on","halt_if_type":"str","halt_if_compare":"is","outputs":2,"output_only_on_state_change":true,"for":"","forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"x":130,"y":380,"wires":[["54bf831c.5a352c"],[]]},{"id":"e97fecdf.962f6","type":"server","name":"Home Assistant","legacy":false,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]`

**Comment by domoticafacilconjota** [comment]
¡Hecho! Muchas gracias por colaborar 😎
