### ISSUE TITLE
[NuevoFlow] Encender o apagar radiador en funcion de apertura y cierra de puertas y ventanas

### ISSUE THREAD

**Issue by TripitonPT** [domoticafacilconjota/capitulos#50]
**Explicación de lo que debe hacer el flow en Node RED**
Hay 4 ventanas y una puerta, que en función de su estado, apagarán el radiador o lo pondrán en su programación automática:

![esquema](https://user-images.githubusercontent.com/76565446/103249130-14da1980-496e-11eb-9872-385c103d264d.jpg)

Para el apagado del radiador:
1- En el caso de que la puerta del tendedero esté cerrada, solo se tiene en cuenta el estado de las ventanas de la cocina. Al abrirse alguna de las ventanas de la cocina, el radiador se apaga.
2.- En el caso de que la puerta del tendedero esté abierta, si se abre cualquiera de las cuatro ventanas (de la cocina o del tendedero), el radiador se apaga.
3.- Si las ventanas de la cocina están cerradas, y en el tendedero hay alguna ventana abierta, en el momento de abrir la puerta del tendedero el radiador se apaga.

Para el encendido del radiador:
1- En el caso de que la puerta del tendedero esté cerrada, solo se tiene en cuenta el estado de las ventanas de la cocina. Al cerrarse las ventanas de la cocina, el radiador se pone en automático.
2.- En el caso de que la puerta del tendedero esté abierta, deben estar cerradas las dos ventanas de la cocina y las dos ventanas del tendedero para que el radiador se ponga en automático.
3.- Si las ventanas de la cocina están cerradas, y en el tendedero hay alguna ventana abierta, en el momento de cerrar la puerta del tendedero el radiador se pone en automático.

Adjunto la descripción de mis nodos que ponen en automático y apagan ese radiador por si le es de utilidad a alguien:

![auto](https://user-images.githubusercontent.com/76565446/103250071-71d7ce80-4972-11eb-9195-cf33ec20ad0a.jpg)

![off](https://user-images.githubusercontent.com/76565446/103250075-7d2afa00-4972-11eb-99c2-b61c60602e85.jpg)

**Notas del autor**

En este flow se busca cambiar entre los estados auto y off del radiador, aunque existe un tercer estado que es el on para cuando se activa manualmente. Lo he ignorado, ya que se supone que si se fuerza la calefacción manualmente es para mantener la puerta y las ventanas cerradas.

**Comment by ortigosano** [comment]
interesado!

**Comment by TripitonPT** [comment]
Muy buenas! Ya me siento mayor! He conseguido hacer el flow y parece que funciona. Estoy convencido de que se podría hacer usando la cuarta parte de nodos que he usado yo, pero funciona, que es lo que me importa. Os lo dejo aquí por si a alguien le interesa:

[{"id":"a9f79ed7.84b3a","type":"tab","label":"Calefacción cocina","disabled":false,"info":""},{"id":"c587e3eb.2d605","type":"server-state-changed","z":"a9f79ed7.84b3a","name":"Ventana cocina 1","server":"4c5022cf.b6cdbc","version":1,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"binary_sensor.ventana_1_cocina_contact","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"on","halt_if_type":"str","halt_if_compare":"is","outputs":2,"output_only_on_state_change":true,"for":0,"forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"x":160,"y":160,"wires":[["e709ef2c.df5f7"],["e9a9475f.0d53f8"]]},{"id":"7e32a8aa.ac1518","type":"server-state-changed","z":"a9f79ed7.84b3a","name":"Ventana cocina 2","server":"4c5022cf.b6cdbc","version":1,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"binary_sensor.ventana_2_cocina_contact","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"on","halt_if_type":"str","halt_if_compare":"is","outputs":2,"output_only_on_state_change":true,"for":0,"forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"x":160,"y":220,"wires":[["e709ef2c.df5f7"],["e9a9475f.0d53f8"]]},{"id":"3576b51e.51d07a","type":"inject","z":"a9f79ed7.84b3a","name":"Forzar ventanas abiertas","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":1050,"y":40,"wires":[["e709ef2c.df5f7"]]},{"id":"3508e8fd.6498d8","type":"api-call-service","z":"a9f79ed7.84b3a","name":"Calefacción cocina en automático","server":"4c5022cf.b6cdbc","version":1,"debugenabled":false,"service_domain":"climate","service":"set_hvac_mode","entityId":"climate.cocina","data":"{\"hvac_mode\":\"auto\"}","dataType":"json","mergecontext":"","output_location":"","output_location_type":"none","mustacheAltTags":false,"x":1420,"y":500,"wires":[[]]},{"id":"e709ef2c.df5f7","type":"api-call-service","z":"a9f79ed7.84b3a","name":"Calefacción cocina apagada","server":"4c5022cf.b6cdbc","version":1,"debugenabled":false,"service_domain":"climate","service":"set_hvac_mode","entityId":"climate.cocina","data":"{\"hvac_mode\":\"off\"}","dataType":"json","mergecontext":"","output_location":"","output_location_type":"none","mustacheAltTags":false,"x":1040,"y":140,"wires":[[]]},{"id":"73b99609.363128","type":"inject","z":"a9f79ed7.84b3a","name":"Forzar ventanas cerradas","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":1390,"y":580,"wires":[["3508e8fd.6498d8"]]},{"id":"37710060.ffdf5","type":"server-state-changed","z":"a9f79ed7.84b3a","name":"Ventana tendedero 1","server":"4c5022cf.b6cdbc","version":1,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"binary_sensor.0x00158d00044ead4f_contact","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"on","halt_if_type":"str","halt_if_compare":"is","outputs":2,"output_only_on_state_change":true,"for":0,"forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"x":170,"y":280,"wires":[["755c01f6.b012b"],["40221a59.55a6d4"]]},{"id":"51a7aa73.904004","type":"server-state-changed","z":"a9f79ed7.84b3a","name":"Ventana tendedero 2","server":"4c5022cf.b6cdbc","version":1,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"binary_sensor.0x00158d00044efa15_contact","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"on","halt_if_type":"str","halt_if_compare":"is","outputs":2,"output_only_on_state_change":true,"for":0,"forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"x":170,"y":340,"wires":[["755c01f6.b012b"],["40221a59.55a6d4"]]},{"id":"755c01f6.b012b","type":"api-current-state","z":"a9f79ed7.84b3a","name":"Puerta tendedero","server":"4c5022cf.b6cdbc","version":1,"outputs":2,"halt_if":"on","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"binary_sensor.0x00158d000465550f_contact","state_type":"str","state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","blockInputOverrides":false,"x":510,"y":260,"wires":[["e709ef2c.df5f7"],[]]},{"id":"a302e1a1.81e79","type":"api-current-state","z":"a9f79ed7.84b3a","name":"Ventana cocina 2","server":"4c5022cf.b6cdbc","version":1,"outputs":2,"halt_if":"on","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"binary_sensor.ventana_2_cocina_contact","state_type":"str","state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","blockInputOverrides":false,"x":510,"y":760,"wires":[[],["3508e8fd.6498d8"]]},{"id":"49d4ba6e.2f8b94","type":"api-current-state","z":"a9f79ed7.84b3a","name":"Ventana cocina 1","server":"4c5022cf.b6cdbc","version":1,"outputs":2,"halt_if":"on","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"binary_sensor.ventana_1_cocina_contact","state_type":"str","state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","blockInputOverrides":false,"x":510,"y":700,"wires":[[],["a302e1a1.81e79"]]},{"id":"301e719e.3ff41e","type":"api-current-state","z":"a9f79ed7.84b3a","name":"Ventana tendedero 1","server":"4c5022cf.b6cdbc","version":1,"outputs":2,"halt_if":"on","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"binary_sensor.0x00158d00044ead4f_contact","state_type":"str","state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","blockInputOverrides":false,"x":820,"y":320,"wires":[[],["817c4dee.71803"]]},{"id":"817c4dee.71803","type":"api-current-state","z":"a9f79ed7.84b3a","name":"Ventana tendedero 2","server":"4c5022cf.b6cdbc","version":1,"outputs":2,"halt_if":"on","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"binary_sensor.0x00158d00044efa15_contact","state_type":"str","state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","blockInputOverrides":false,"x":1080,"y":320,"wires":[[],["3508e8fd.6498d8"]]},{"id":"dcbc986a.70bcf8","type":"api-current-state","z":"a9f79ed7.84b3a","name":"Puerta tendedero","server":"4c5022cf.b6cdbc","version":1,"outputs":2,"halt_if":"on","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"binary_sensor.0x00158d000465550f_contact","state_type":"str","state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","blockInputOverrides":false,"x":510,"y":440,"wires":[["301e719e.3ff41e","1aea973b.aa0679"],["3508e8fd.6498d8"]]},{"id":"1aea973b.aa0679","type":"api-current-state","z":"a9f79ed7.84b3a","name":"Ventana tendedero 2","server":"4c5022cf.b6cdbc","version":1,"outputs":2,"halt_if":"on","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"binary_sensor.0x00158d00044efa15_contact","state_type":"str","state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","blockInputOverrides":false,"x":820,"y":380,"wires":[[],["a04e5440.62c4f8"]]},{"id":"a04e5440.62c4f8","type":"api-current-state","z":"a9f79ed7.84b3a","name":"Ventana tendedero 1","server":"4c5022cf.b6cdbc","version":1,"outputs":2,"halt_if":"on","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"binary_sensor.0x00158d00044ead4f_contact","state_type":"str","state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","blockInputOverrides":false,"x":1080,"y":380,"wires":[[],["3508e8fd.6498d8"]]},{"id":"7f15860e.03f8a8","type":"api-current-state","z":"a9f79ed7.84b3a","name":"Puerta tendedero","server":"4c5022cf.b6cdbc","version":1,"outputs":2,"halt_if":"on","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"binary_sensor.0x00158d000465550f_contact","state_type":"str","state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","blockInputOverrides":false,"x":510,"y":640,"wires":[["49d4ba6e.2f8b94"],[]]},{"id":"64caabd6.2062e4","type":"server-state-changed","z":"a9f79ed7.84b3a","name":"Puerta tendedero","server":"4c5022cf.b6cdbc","version":1,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"binary_sensor.0x00158d000465550f_contact","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"on","halt_if_type":"str","halt_if_compare":"is","outputs":2,"output_only_on_state_change":true,"for":0,"forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"x":160,"y":40,"wires":[["9899fea5.7ce7b","87e40d3e.82f59"],[]]},{"id":"e9a9475f.0d53f8","type":"api-current-state","z":"a9f79ed7.84b3a","name":"Ventana cocina 1","server":"4c5022cf.b6cdbc","version":1,"outputs":2,"halt_if":"on","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"binary_sensor.ventana_1_cocina_contact","state_type":"str","state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","blockInputOverrides":false,"x":510,"y":320,"wires":[[],["4d4841a2.974ba"]]},{"id":"4d4841a2.974ba","type":"api-current-state","z":"a9f79ed7.84b3a","name":"Ventana cocina 2","server":"4c5022cf.b6cdbc","version":1,"outputs":2,"halt_if":"on","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"binary_sensor.ventana_2_cocina_contact","state_type":"str","state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","blockInputOverrides":false,"x":510,"y":380,"wires":[[],["dcbc986a.70bcf8"]]},{"id":"40221a59.55a6d4","type":"api-current-state","z":"a9f79ed7.84b3a","name":"Ventana tendedero 1","server":"4c5022cf.b6cdbc","version":1,"outputs":2,"halt_if":"on","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"binary_sensor.0x00158d00044ead4f_contact","state_type":"str","state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","blockInputOverrides":false,"x":520,"y":520,"wires":[[],["f0e4ec4a.74bb9"]]},{"id":"f0e4ec4a.74bb9","type":"api-current-state","z":"a9f79ed7.84b3a","name":"Ventana tendedero 2","server":"4c5022cf.b6cdbc","version":1,"outputs":2,"halt_if":"on","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"binary_sensor.0x00158d00044efa15_contact","state_type":"str","state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","blockInputOverrides":false,"x":520,"y":580,"wires":[[],["7f15860e.03f8a8"]]},{"id":"9899fea5.7ce7b","type":"api-current-state","z":"a9f79ed7.84b3a","name":"Ventana tendedero 1","server":"4c5022cf.b6cdbc","version":1,"outputs":2,"halt_if":"on","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"binary_sensor.0x00158d00044ead4f_contact","state_type":"str","state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","blockInputOverrides":false,"x":520,"y":40,"wires":[["e709ef2c.df5f7"],[]]},{"id":"87e40d3e.82f59","type":"api-current-state","z":"a9f79ed7.84b3a","name":"Ventana tendedero 2","server":"4c5022cf.b6cdbc","version":1,"outputs":2,"halt_if":"on","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"binary_sensor.0x00158d00044efa15_contact","state_type":"str","state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","blockInputOverrides":false,"x":520,"y":100,"wires":[["e709ef2c.df5f7"],[]]},{"id":"52ad0347.eec90c","type":"server-state-changed","z":"a9f79ed7.84b3a","name":"Puerta tendedero","server":"4c5022cf.b6cdbc","version":1,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"binary_sensor.0x00158d000465550f_contact","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"on","halt_if_type":"str","halt_if_compare":"is","outputs":2,"output_only_on_state_change":true,"for":0,"forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"x":160,"y":700,"wires":[[],["49d4ba6e.2f8b94"]]},{"id":"fb0ecf98.02ff9","type":"comment","z":"a9f79ed7.84b3a","name":"Explicación del flow","info":"1.- Cuando cualquier ventana de la cocina se abre, la calefacción se apaga.\n2.- Cuando cualquier ventana del tendedero se abre, si la puerta del tendedero esta abierta, la calefacción se apaga.\n3.- Si se abre la puerta del tendedero y alguna de las ventanas del tendedero esá abierta, la calefacción se apaga.\n4.- Si se cierra la puerta del tendedero y las ventanas de la cocina están cerradas, pone la calefacción en automático.\n5.- Si se cierra una ventana del tendedero, revisa que la otra ventana del tendedero y las otras dos de la cocina estén cerradas. Si lo están, pone la calefacción en automático.\n6.- Si se cierra una ventana de la cocina, revisa que la otra ventana de la cocina esté cerrada. Si lo está y la puerta del tendedero está cerrada, pone la calefacción en automático.\n7.- Si se cierra una ventana de la cocina, revisa que la otra ventana de la cocina esté cerrada. Si lo está y la puerta del tendedero está abierta, comprueba que las ventanas del tendedero estén cerradas. Si lo están, pone la calefacción en automático.","x":170,"y":540,"wires":[]},{"id":"4c5022cf.b6cdbc","type":"server","name":"Home Assistant","addon":true}]
