### ISSUE TITLE
[Sugerencia] Tasmotizar una esp32cam

### ISSUE THREAD

**Issue by fjterrada69** [domoticafacilconjota/capitulos#56]
**Me gustaría sugerir que hagas un vídeo con el siguiente contenido:**
Borra sólo esta línea ¡Recuerda detallar todo bien para no dejarme nada atrás!

**Comment by fjterrada69** [comment]
> **Me gustaría sugerir que hagas un vídeo con el siguiente contenido:**
> Borra sólo esta línea ¡Recuerda detallar todo bien para no dejarme nada atrás!

**Comment by AnibalVaz** [comment]
si de algo sirve, tasmota no permite flashear ESP32, pero ESPHome, es el ideal para tu ESP32CAM, https://esphome.io/components/esp32_camera.html , tengo todo mi hogar domótizado con ESP32, uno por habitacion y cada dia le voy integrando algo nuevo...
