### ISSUE TITLE
[Sugerencia] Node Red: Nodos de tiempo

### ISSUE THREAD

**Issue by marcospg75** [domoticafacilconjota/capitulos#6]
**Me gustaría sugerir que hagas un vídeo con el siguiente contenido:**
Hola, me gustaría que hicieras un vídeo de NodeRed hablando y explicando nodos útiles para tareas repetitivas en el tiempo... por ejemplo:

Despertadores: Que puedes programar a una hora entre semana y a otra hora el fin de semana
Climatización: Donde cada día de la semana puedes tener una configuración diferente (aquí, también relacionado con el tiempo, habría que controlar la hora para poner una temperatura u otra)
Eventos que se deben activar al amanecer, al atardecer...

En definitiva, automatismos que se disparan con el tiempo... que hay muchos :)

PD: Mil gracias por tus vídeos!!! Acabo de enlazar mis primeros enchufes Zigbee por Zigbee2MQTT :)

**Comment by domoticafacilconjota** [comment]
¡Hola! https://youtu.be/aRNtIltj9Y8 y https://youtu.be/Sw1ZbWgPL6U con esos dos creo que puedo cerrar el issue. De no ser así haz un comentario y lo miramos.
